### PR TITLE
Remove lsp and files

### PR DESCRIPTION
**Pull request by BinderDavid**
Remove more code that we do not use inside polarity. Also gets rid of a dependency on the `lsp-types` library.

### CODE REVIEW

**Comment by BinderDavid** [comment]
I checked locally that polarity still works if we depend on that commit.

**Comment by timsueberkrueb** [comment]
:+1: We only seem to be using `Span`, `ByteIndex`, `ByteOffset`, `Location`, `File`.

**Review by timsueberkrueb — APPROVED** [review]

**Comment by timsueberkrueb** [comment]
If we can trim this down even further, we could consider moving it to the main Polarity repo. I.e. `Span`, `ByteIndex`, `ByteOffset`, `Location` could probably live in `ast`, `File` could live in `driver`. We need to make sure to include the original license, copyright notice and attribution, though.

**Comment by BinderDavid** [comment]
> If we can trim this down even further, we could consider moving it to the main Polarity repo. I.e. `Span`, `ByteIndex`, `ByteOffset`, `Location` could probably live in `ast`, `File` could live in `driver`. We need to make sure to include the original license, copyright notice and attribution, though.

Yup, I also wrote something similar in the `engineering` channel on Discord :)

**Pull request merged**
